// venues-plan.md §3/§6 (A6 P2 pass): enrichment for the 51-row P2 leads queue in
// data/venues/leads-to-enrich.csv. Researched 2026-08-17 via 6 parallel WebSearch/WebFetch agents
// against each operator's own site (a secondary directory like badmintoncourt.au used only where
// the operator's own site didn't carry the field, and always marked medium/low confidence).
//
// The P2 queue snapshot was stale: 9 of the 51 leads' place_ids already exist as low-confidence
// `data_source='csv'` rows from the original A2 seed ingest (20260815001400) — those are UPDATEs
// here, not new venues. 1 more (Alpha Slough) was already enriched in the P1 chain pass
// (20260815001500) under a different display name. 5 more (NBC Seven Hills/Alexandria/Castle
// Hill/MQ Park/Olympic Park) were also already done in that same P1 chain pass. Net: of 51 leads,
// 21 are genuinely new venues, 9 upgrade an existing low-confidence row, 1 upgrades UNSW FAC
// (found via UNSW Fitness & Aquatic Centre (B5), same place_id as the existing
// 'unsw-fitness-aquatic-centre' row), and 16 were confirmed to have NO badminton (or are exact
// duplicates of another row already handled) and are deliberately not inserted — see NO_BADMINTON
// below for the record.
//
// Usage: node scripts/venues/enrich-p2.mjs
// Output: supabase/migrations/<timestamp>_p2_enrichment.sql — review before pushing.

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const MIGRATIONS = resolve(ROOT, "supabase/migrations");

function sqlStr(v) {
  if (v === null || v === undefined) return "null";
  return `'${String(v).replace(/'/g, "''")}'`;
}
function sqlBool(v) {
  if (v === null || v === undefined) return "null";
  return v ? "true" : "false";
}
function sqlArr(vals) {
  return `array[${vals.join(",")}]`;
}
function sqlJsonb(obj) {
  if (!obj) return "null";
  // drop nights left as JS `null` (unknown day) so we don't store a bogus empty array
  const cleaned = Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== null));
  return `'${JSON.stringify(cleaned).replace(/'/g, "''")}'::jsonb`;
}
function slugify(name) {
  return name
    .toLowerCase()
    .replace(/\([^)]*\)/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Records with an explicit `slug` matching an existing venues.slug are UPDATEs (the on-conflict
// path resolves to the existing row); everything else is a genuinely new venue.
const VENUES = [
  // ---- new venues ----
  {
    name: "Blacktown Leisure Centre Stanhope",
    suburb: "Stanhope Gardens",
    state: "NSW",
    address: "Stanhope Pkwy & Sentry Dr, Stanhope Gardens NSW 2768",
    lat: -33.7195019,
    lng: 150.9213557,
    place_id: "ChIJB9jAkDyfEmsRfOWgUKpFJHI",
    courts_badminton: null,
    courts_total: 4,
    dedicated: false,
    surface: "synthetic",
    bookability: "public",
    booking_platform: "ActiveCarrot",
    booking_url: "https://secure.activecarrot.com/public/facility/browse/1102/1279",
    website_url: "https://www.blacktownaquaticandsports.com.au/About/Our-venues/Blacktown-Leisure-Centre-Stanhope",
    phone: "02 9421 2600",
    opening_hours: { mon: [["06:00", "21:00"]], tue: [["06:00", "21:00"]], wed: [["06:00", "21:00"]], thu: [["06:00", "21:00"]], fri: [["06:00", "21:00"]], sat: [["08:00", "17:00"]], sun: [["08:00", "17:00"]] },
    access_notes: "Stadium is 4 multi-use indoor courts shared between badminton, pickleball, squash and other sports; book via ActiveCarrot portal or phone.",
    price_bands: [{ label: "Court hire", days: [1, 2, 3, 4, 5, 6, 7], cents: 3900, unit: "court_hour", notes: "~$39/hr, approximate — cross-checked against a secondary listing" }],
    data_source: "operator",
    source_url: "https://www.blacktownaquaticandsports.com.au/About/Our-venues/Blacktown-Leisure-Centre-Stanhope",
    confidence: "medium",
  },
  {
    name: "Menai Indoor Sports Centre",
    suburb: "Menai",
    state: "NSW",
    address: "98-150 Allison Cres, Menai NSW 2234",
    lat: -34.0119326,
    lng: 151.0152149,
    place_id: "ChIJrfhTYprAEmsR2ieIjiFYZbw",
    courts_badminton: null,
    courts_total: 4,
    dedicated: false,
    surface: "synthetic",
    bookability: "public",
    booking_platform: "Attekus / Sutherland Shire Council online booking",
    booking_url: "https://sutherland.bookable.net.au/venues/314/menai-indoor-sports-centre",
    website_url: "https://www.sutherlandshire.nsw.gov.au/Outdoors/Leisure-Centres/Centres/Menai-Indoor-Sports-Centre",
    phone: "(02) 9532 0444",
    opening_hours: { mon: [["09:00", "22:00"]], tue: [["09:00", "22:00"]], wed: [["09:00", "22:00"]], thu: [["09:00", "22:00"]], fri: [["09:00", "22:00"]], sat: [["08:30", "15:30"]], sun: [] },
    access_notes: "4 multi-purpose courts hosting badminton alongside basketball, netball, indoor soccer, volleyball, gymnastics, martial arts and dance programs. Sunday availability is by request rather than fixed public hours.",
    price_bands: [],
    data_source: "operator",
    source_url: "https://www.sutherlandshireaustralia.com.au/5122/menai-indoor-sports-centre/",
    confidence: "medium",
  },
  {
    name: "Willoughby Leisure Centre",
    suburb: "Willoughby",
    state: "NSW",
    address: "2 Small St, Willoughby NSW 2068",
    lat: -33.8115509,
    lng: 151.2037048,
    place_id: "ChIJWQFBVDypEmsRW7A__buPlw8",
    courts_badminton: null,
    courts_total: 4,
    dedicated: false,
    surface: "synthetic",
    bookability: "public",
    booking_platform: "ActiveCarrot",
    booking_url: "https://secure.activecarrot.com/public/facility/overlay/1242/1454",
    website_url: "https://www.willoughbyleisure.com.au/Facilities-and-opening-hours/Sports-Hall",
    phone: "02 9958 5799",
    opening_hours: { mon: [["06:00", "22:00"]], tue: [["06:00", "22:00"]], wed: [["06:00", "22:00"]], thu: [["06:00", "22:00"]], fri: [["06:00", "22:00"]], sat: [["07:00", "19:00"]], sun: [["07:00", "19:00"]] },
    access_notes: "4 mixed-purpose sports hall courts. Home of the Willoughby Badminton Association (club sessions Sat/Sun afternoons, visitors welcome) alongside general public casual hire.",
    price_bands: [{ label: "Court hire", days: [1, 2, 3, 4, 5, 6, 7], cents: 3000, unit: "court_hour", notes: null }],
    data_source: "operator",
    source_url: "https://www.willoughbyleisure.com.au/Facilities-and-opening-hours/Sports-Hall",
    confidence: "medium",
  },
  {
    name: "Ultimo Community Centre",
    suburb: "Ultimo",
    state: "NSW",
    address: "40 William Henry St corner Bulwara Rd, Ultimo NSW 2007",
    lat: -33.877977,
    lng: 151.198002,
    place_id: "ChIJ64EYny-uEmsRxaJRkE5K53o",
    courts_badminton: null,
    courts_total: 1,
    dedicated: false,
    surface: "other",
    bookability: "public",
    booking_platform: null,
    booking_url: null,
    website_url: "https://www.cityofsydney.nsw.gov.au/sports-facilities/outdoor-court-ultimo-community-centre",
    phone: "02 9298 3111",
    opening_hours: { mon: [["10:00", "20:00"]], tue: [["10:00", "20:00"]], wed: [["10:00", "20:00"]], thu: [["10:00", "20:00"]], fri: [["10:00", "20:00"]], sat: [["10:00", "16:00"]], sun: [["10:00", "16:00"]] },
    access_notes: "Single multi-purpose indoor court suitable for basketball, volleyball, badminton, indoor soccer, futsal and pickleball. Equipment for purchase/hire on site. Closed public holidays.",
    price_bands: [
      { label: "Indoor court hire - standard", days: [1, 2, 3, 4, 5, 6, 7], cents: 3100, unit: "court_hour", notes: null },
      { label: "Indoor court hire - concession", days: [1, 2, 3, 4, 5, 6, 7], cents: 2200, unit: "court_hour", notes: null },
    ],
    data_source: "operator",
    source_url: "https://www.cityofsydney.nsw.gov.au/sports-facilities/outdoor-court-ultimo-community-centre",
    confidence: "medium",
  },
  {
    name: "Perry Park Recreation Centre",
    suburb: "Alexandria",
    state: "NSW",
    address: "1B Maddox St, Alexandria NSW 2015",
    lat: -33.9080236,
    lng: 151.1958329,
    place_id: "ChIJ12D1kXqxEmsRkZcv5ozfotI",
    courts_badminton: null,
    courts_total: 4,
    dedicated: false,
    surface: "other",
    bookability: "public",
    booking_platform: null,
    booking_url: null,
    website_url: "https://www.cityofsydney.nsw.gov.au/community-centres/perry-park-recreation-centre",
    phone: "02 9265 9182",
    opening_hours: { mon: [["10:00", "23:00"]], tue: [["10:00", "23:00"]], wed: [["10:00", "23:00"]], thu: [["10:00", "23:00"]], fri: [["10:00", "22:00"]], sat: [["08:00", "20:30"]], sun: [["09:00", "20:00"]] },
    access_notes: "4 multipurpose indoor courts shared across basketball, netball, volleyball, badminton and futsal. City of Sydney-operated. Change facilities, showers, kiosk, free WiFi on site.",
    price_bands: [],
    data_source: "operator",
    source_url: "https://www.cityofsydney.nsw.gov.au/community-centres/perry-park-recreation-centre",
    confidence: "medium",
  },
  {
    name: "PCYC Hawkesbury",
    suburb: "South Windsor",
    state: "NSW",
    address: "16 Stewart St, South Windsor NSW 2756",
    lat: -33.6270853,
    lng: 150.8042255,
    place_id: "ChIJeTEF_ledEmsRFWh0ShgkD7k",
    courts_badminton: null,
    courts_total: 6,
    dedicated: false,
    surface: "other",
    bookability: "public",
    booking_platform: null,
    booking_url: null,
    website_url: "https://www.pcycnsw.org.au/hawkesbury/",
    phone: "(02) 4505 5070",
    opening_hours: { mon: [["06:00", "21:30"]], tue: [["06:00", "21:30"]], wed: [["06:00", "21:30"]], thu: [["06:00", "21:30"]], fri: [["06:00", "21:30"]], sat: [["08:00", "16:00"]], sun: [["10:00", "16:00"]] },
    access_notes: "Six-court indoor stadium shared across futsal, netball, basketball, volleyball and badminton. Casual court hire; bring own equipment. Booking by phone/email (hawkesbury@pcycnsw.org.au).",
    price_bands: [{ label: "Casual badminton court hire", days: [1, 2, 3, 4, 5, 6, 7], cents: 4000, unit: "court_hour", notes: null }],
    data_source: "operator",
    source_url: "https://www.pcycnsw.org.au/sports-recreation/badminton/",
    confidence: "high",
  },
  {
    name: "JS Sports Arena",
    suburb: "Smeaton Grange",
    state: "NSW",
    address: "75 Anderson Rd, Smeaton Grange NSW 2567",
    lat: -34.0340635,
    lng: 150.7611892,
    place_id: "ChIJL-zc1UvxEmsRtIg6tlEhDd8",
    courts_badminton: 11,
    courts_total: 11,
    dedicated: true,
    surface: "timber",
    bookability: "public",
    booking_platform: "SportLogic",
    booking_url: "https://jssportsarena.sportlogic.net.au/secure/customer/home",
    website_url: "https://jssportsarena.com.au/",
    phone: "+61 490 135 009",
    opening_hours: null,
    access_notes: "Dedicated indoor badminton/pickleball facility, sprung wooden floors, BWF-approved mats. 11 total courts split between badminton and pickleball (split not published). Racket hire ($5) and stringing available.",
    price_bands: [
      { label: "Weekday off-peak", days: [1, 2, 3, 4, 5], cents: 2500, unit: "court_hour", notes: "6am-6pm" },
      { label: "Weekday peak", days: [1, 2, 3, 4, 5], cents: 3400, unit: "court_hour", notes: "6pm-10pm" },
      { label: "Weekend peak", days: [6, 7], cents: 3400, unit: "court_hour", notes: "6am-12pm" },
      { label: "Weekend off-peak", days: [6, 7], cents: 2800, unit: "court_hour", notes: "12pm-10pm" },
      { label: "Late night (all days)", days: [1, 2, 3, 4, 5, 6, 7], cents: 2800, unit: "court_hour", notes: "10pm onwards" },
    ],
    data_source: "operator",
    source_url: "https://jssportsarena.com.au/rates.html",
    confidence: "high",
  },
  {
    name: "Bernie Mullane Sports Complex",
    suburb: "Kellyville",
    state: "NSW",
    address: "10 Marella Ave, Kellyville NSW 2155",
    lat: -33.7037593,
    lng: 150.9679784,
    place_id: "ChIJL4mHYdehEmsRaAYnlLTOppQ",
    courts_badminton: 6,
    courts_total: 6,
    dedicated: false,
    surface: "timber",
    bookability: "public",
    booking_platform: null,
    booking_url: null,
    website_url: "https://berniemullane.com.au/",
    phone: "02 8824 3522",
    opening_hours: { mon: [["08:00", "22:00"]], tue: [["08:00", "22:00"]], wed: [["08:00", "22:00"]], thu: [["08:00", "22:00"]], fri: [["08:00", "22:00"]], sat: [["08:00", "21:00"]], sun: [["08:00", "21:00"]] },
    access_notes: "Multi-purpose indoor courts (basketball/futsal/badminton) with sprung wooden flooring, run by The Hills Shire Council. Badminton nets/line-marking provided on request, not a dedicated venue.",
    price_bands: [],
    data_source: "operator",
    source_url: "https://berniemullane.com.au/about/opening-hours/",
    confidence: "medium",
  },
  {
    name: "KGV Recreation Centre",
    suburb: "The Rocks",
    state: "NSW",
    address: "15 Cumberland St, The Rocks NSW 2000",
    lat: -33.8596386,
    lng: 151.206611,
    place_id: "ChIJSytgJF2uEmsRVZ0iEjbLdfE",
    courts_badminton: 6,
    courts_total: null,
    dedicated: false,
    surface: null,
    bookability: "public",
    booking_platform: "City of Sydney online booking / What's On",
    booking_url: "https://whatson.cityofsydney.nsw.gov.au/events/kgv-casual-badminton",
    website_url: "https://www.cityofsydney.nsw.gov.au/community-centres/king-george-v-kgv-recreation-centre",
    phone: "02 9265 9868",
    opening_hours: null,
    access_notes: "Run by City of Sydney. Confirmed program is a scheduled casual/social badminton session (Tue 7-9am, all levels) — general facility hours for other court-hire not published.",
    price_bands: [{ label: "Casual badminton session (adult)", days: [2], cents: 650, unit: "person_session", notes: "Tuesdays 7-9am" }],
    data_source: "operator",
    source_url: "https://whatson.cityofsydney.nsw.gov.au/events/kgv-casual-badminton",
    confidence: "medium",
  },
  {
    name: "Robyn Webster Sports Centre",
    suburb: "Tempe",
    state: "NSW",
    address: "Holbeach Ave, Tempe NSW 2044",
    lat: -33.9314439,
    lng: 151.1607025,
    place_id: "ChIJ3ab8c5KwEmsRbAKv5gT7ypo",
    courts_badminton: 8,
    courts_total: null,
    dedicated: false,
    surface: "timber",
    bookability: "public",
    booking_platform: "PerfectMind",
    booking_url: "https://innerwest.perfectmind.com/40526/Reports/BookMe4?widgetId=e9a6c34e-79ed-45bd-a585-c4d3641b30ea",
    website_url: "https://www.innerwest.nsw.gov.au/indoor-sporting-centres/robyn-webster-sports-centre",
    phone: "(02) 9392 5515",
    opening_hours: null,
    access_notes: "Jointly managed: Inner West Council weekdays 8am-4pm, Sat 8am-12pm, Wed 4pm-10:30pm; Sydney Uni Sport (SUSF) manages other times (phone (02) 9351 4978). Sprung timber floor, 8 badminton courts alongside volleyball/futsal/netball.",
    price_bands: [],
    data_source: "operator",
    source_url: "https://www.innerwest.nsw.gov.au/indoor-sporting-centres/robyn-webster-sports-centre",
    confidence: "high",
  },
  {
    name: "Gameday ANZ",
    suburb: "Riverstone",
    state: "NSW",
    address: "10 Edward St, Riverstone NSW 2765",
    lat: -33.6659678,
    lng: 150.8567018,
    place_id: "ChIJn9PbE1adEmsRYEgFGOs3iXQ",
    courts_badminton: null,
    courts_total: null,
    dedicated: false,
    surface: null,
    bookability: "public",
    booking_platform: "Sportlogic",
    booking_url: "https://gamedayanz.sportlogic.net.au",
    website_url: "https://www.gamedayanz.com.au/",
    phone: "0410 466 760",
    opening_hours: null,
    access_notes: "Operator confirms indoor courts for badminton, pickleball and basketball under one roof. Court count, surface, hours and per-hour pricing not published — only bulk court-hire credit packages.",
    price_bands: [],
    data_source: "operator",
    source_url: "https://www.gamedayanz.com.au/",
    confidence: "medium",
  },
  {
    name: "Riverstone Sports Centre",
    suburb: "Grantham Farm",
    state: "NSW",
    address: "15 Hamilton St cnr Garfield Rd E, Grantham Farm NSW 2765",
    lat: -33.673848,
    lng: 150.870869,
    place_id: "ChIJeTh2bXueEmsREPTy-Wh9AQ8",
    courts_badminton: null,
    courts_total: null,
    dedicated: false,
    surface: null,
    bookability: "club_only",
    club_contact: "Let's Badminton club — Dinesh 0421 445 060",
    booking_platform: "Skedda",
    booking_url: null, // bookability <> 'public', per venues-plan §4.2
    website_url: "https://rivochurch.com/rsc/badminton/",
    phone: "02 9627 5148",
    opening_hours: { mon: [], tue: [["06:00", "07:00"]], wed: [], thu: [["06:00", "07:00"]], fri: [], sat: [["06:00", "07:00"]], sun: [["06:00", "07:00"]] },
    access_notes: "Club-hired hall — badminton run by the 'Let's Badminton' club, not open to public drop-in. New players need a reference from an existing player or admin skill-assessment (24-48hr approval). Sessions Tue/Thu/Sat/Sun. Book via letsbadminton.skedda.com.",
    price_bands: [],
    data_source: "operator",
    source_url: "https://rivochurch.com/rsc/badminton/",
    confidence: "medium",
  },
  {
    name: "Sydney Uni Sport",
    suburb: "Darlington",
    state: "NSW",
    address: "Cnr Codrington St and Darlington Ln, Darlington NSW 2008",
    lat: -33.8911668,
    lng: 151.1917502,
    place_id: "ChIJ1Tf4v9OxEmsR4MXiVIiMqSM",
    courts_badminton: 6,
    courts_total: null,
    dedicated: false,
    surface: "other",
    bookability: "members_only",
    booking_platform: null,
    booking_url: "https://susf.com.au/online-bookings/",
    website_url: "https://susf.com.au/sports-aquatic-centre/",
    phone: "(02) 9351 4978",
    opening_hours: { mon: [["05:30", "22:00"]], tue: [["05:30", "22:00"]], wed: [["05:30", "22:00"]], thu: [["05:30", "22:00"]], fri: [["05:30", "22:00"]], sat: [["06:00", "20:00"]], sun: [["07:00", "22:00"]] },
    access_notes: "Sports & Aquatic Centre (SAC) building. Online booking restricted to active SUSF Annual Members; casual bookings go through phone. Distinct building from Robyn Webster Sports Centre and The Arena (both also SUSF-managed, both separate directory rows).",
    price_bands: [],
    data_source: "operator",
    source_url: "https://susf.com.au/squash-tennis-courts/",
    confidence: "medium",
  },
  {
    name: "PlayPoint Seven Hills",
    suburb: "Seven Hills",
    state: "NSW",
    address: "2/6 Boden Rd, Seven Hills NSW 2147",
    lat: -33.7739475,
    lng: 150.960008,
    place_id: "ChIJPdk_6eGjEmsRO7uheBpaLDA",
    courts_badminton: 8,
    courts_total: 8,
    dedicated: true,
    surface: "mat",
    bookability: "public",
    booking_platform: "HelloClub",
    booking_url: "https://playpoint.helloclub.com",
    website_url: "https://playpoint.com.au/badminton/",
    phone: "1800 903 600",
    opening_hours: { mon: [["00:00", "23:59"]], tue: [["00:00", "23:59"]], wed: [["00:00", "23:59"]], thu: [["00:00", "23:59"]], fri: [["00:00", "23:59"]], sat: [["00:00", "23:59"]], sun: [["00:00", "23:59"]] },
    access_notes: "8 dedicated badminton courts, Taraflex Evolution mats over sprung floor. 24hr access. Social/beginner sessions Thu & Fri 8-10pm.",
    price_bands: [
      { label: "Off-peak court hire", days: [1, 2, 3, 4, 5], cents: 2900, unit: "court_hour", notes: "6am-4pm weekdays" },
      { label: "Peak court hire", days: [1, 2, 3, 4, 5], cents: 3700, unit: "court_hour", notes: "4pm-10pm weekdays" },
      { label: "Weekend off-peak", days: [6, 7], cents: 2900, unit: "court_hour", notes: "12pm-10pm" },
      { label: "Weekend peak", days: [6, 7], cents: 3700, unit: "court_hour", notes: "6am-12pm" },
      { label: "Overnight court hire", days: [1, 2, 3, 4, 5, 6, 7], cents: 2300, unit: "court_hour", notes: "10pm-6am" },
      { label: "Social beginner badminton", days: [4, 5], cents: 1400, unit: "person_hour", notes: "Doubles social session 8-10pm, approx $14/person" },
    ],
    data_source: "operator",
    source_url: "https://playpoint.com.au/rates/",
    confidence: "high",
  },
  {
    name: "PlayPoint Blacktown",
    suburb: "Blacktown",
    state: "NSW",
    address: "2A Bessemer St, Blacktown NSW 2148",
    lat: -33.7570441,
    lng: 150.9126907,
    place_id: "ChIJzYAqVx-ZEmsRjSV1t1Ty37M",
    courts_badminton: null,
    courts_total: null,
    dedicated: false,
    surface: "mat",
    bookability: "public",
    booking_platform: "HelloClub",
    booking_url: "https://playpoint.helloclub.com",
    website_url: "https://playpoint.com.au/badminton/",
    phone: "1800 903 600",
    opening_hours: { mon: [["00:00", "23:59"]], tue: [["00:00", "23:59"]], wed: [["00:00", "23:59"]], thu: [["00:00", "23:59"]], fri: [["00:00", "23:59"]], sat: [["00:00", "23:59"]], sun: [["00:00", "23:59"]] },
    access_notes: "PlayPoint's generic badminton page confirms badminton at this venue (24hr access, HelloClub booking) but doesn't break out per-location court count or pricing.",
    price_bands: [],
    data_source: "partner",
    source_url: "https://playpoint.com.au/badminton/",
    confidence: "low",
  },
  {
    name: "PCYC Marrickville",
    suburb: "Marrickville",
    state: "NSW",
    address: "531 Illawarra Rd, Marrickville NSW 2204",
    lat: -33.9196796,
    lng: 151.1451878,
    place_id: "ChIJZ3am64OwEmsRb9BekLPkryU",
    courts_badminton: 4,
    courts_total: 3,
    dedicated: false,
    surface: "other",
    bookability: "public",
    booking_platform: "ActiveCarrot",
    booking_url: "https://secure.activecarrot.com/public/facility/browse/138/1068",
    website_url: "https://www.pcycnsw.org.au/marrickville/",
    phone: "(02) 9559 7722",
    opening_hours: { mon: [["11:00", "14:00"]], tue: [["10:00", "13:30"]], wed: [["11:00", "14:00"]], thu: [["20:00", "22:00"]], fri: [["20:00", "22:00"]], sun: [["20:00", "22:00"]] },
    access_notes: "3 multi-purpose indoor courts (Debbie & Abbey Borgia Community Recreation Centre); Court 3 lines out to 4 full-size badminton courts. Hours shown are badminton-specific casual/social program times, not full facility hours. 18+ only for these sessions.",
    price_bands: [
      { label: "Casual badminton session", days: [1, 2, 3, 4, 5, 7], cents: 550, unit: "person_session", notes: null },
      { label: "10-session pass", days: [1, 2, 3, 4, 5, 7], cents: 4300, unit: "person_session", notes: "$43 for 10 passes" },
    ],
    data_source: "operator",
    source_url: "https://www.pcycnsw.org.au/marrickville/",
    confidence: "medium",
  },
  {
    name: "Star Smash Sports",
    suburb: "Marsden Park",
    state: "NSW",
    address: "Unit 2A/311 South St, Marsden Park NSW 2765",
    lat: -33.7102619,
    lng: 150.8257979,
    place_id: "ChIJAXPCsymbEmsRVCjMoPq2llc",
    courts_badminton: null,
    courts_total: null,
    dedicated: false,
    surface: null,
    bookability: "public",
    booking_platform: "YepBooking",
    booking_url: "https://starsmashsports.yepbooking.com.au/",
    website_url: null,
    phone: "0428 030 151",
    opening_hours: null,
    access_notes: "Multi-sport indoor facility (badminton, pickleball, indoor cricket, soccer, table tennis; badminton coaching via Sydney Siders Academy). Court count, pricing and hours not confirmed — no working marketing site found.",
    price_bands: [],
    data_source: "operator",
    source_url: "https://starsmashsports.yepbooking.com.au/",
    confidence: "low",
  },
  {
    name: "Michael Clarke Recreation Centre",
    suburb: "Carnes Hill",
    state: "NSW",
    address: "2 Margaret Dawson Dr, Carnes Hill NSW 2171",
    lat: -33.93557,
    lng: 150.8460716,
    place_id: "ChIJwTaN52iTEmsRhUpdG3HiBeA",
    courts_badminton: 8,
    courts_total: 2,
    dedicated: false,
    surface: null,
    bookability: "public",
    booking_platform: null,
    booking_url: "https://www.michaelclarkecentre.com.au/sports/court-hire/",
    website_url: "https://www.michaelclarkecentre.com.au/",
    phone: "+61 2 8760 4800",
    opening_hours: { mon: [["05:00", "22:00"]], tue: [["05:00", "22:00"]], wed: [["05:00", "22:00"]], thu: [["05:00", "22:00"]], fri: [["05:00", "22:00"]], sat: [["07:00", "18:30"]], sun: [["07:00", "18:30"]] },
    access_notes: "Council-operated (Liverpool City Council / Belgravia Leisure) double-court indoor hall used for basketball, badminton, volleyball, futsal; lines down to 8 badminton (quarter-court) layouts.",
    price_bands: [{ label: "Casual court hire (badminton)", days: [1, 2, 3, 4, 5, 6, 7], cents: 8570, unit: "court_hour", notes: "1-hour minimum; separate ~$8.20 casual entry fee may also apply" }],
    data_source: "operator",
    source_url: "https://www.michaelclarkecentre.com.au/sports/court-hire/",
    confidence: "medium",
  },
  {
    name: "Northern Beaches Indoor Sports Centre",
    suburb: "Warriewood",
    state: "NSW",
    address: "Jacksons Rd, Warriewood NSW 2102",
    lat: -33.6988838,
    lng: 151.2959431,
    place_id: "ChIJIQAFSuRUDWsROJcIHPVoA6U",
    courts_badminton: null,
    courts_total: null,
    dedicated: false,
    surface: null,
    bookability: "unknown",
    booking_platform: null,
    booking_url: null,
    website_url: "https://www.indoorsports.net.au/",
    phone: "+61 2 9913 2688",
    opening_hours: null,
    access_notes: "Non-profit-run multipurpose sports halls primarily for basketball/netball/volleyball/indoor soccer; badminton listed only as an activity the halls 'can accommodate', no dedicated court count/hours/pricing found. Do not confuse with the separate PCYC Northern Beaches (Dee Why).",
    price_bands: [],
    data_source: "operator",
    source_url: "https://www.indoorsports.net.au/facility/index.shtml",
    confidence: "low",
  },
  {
    name: "The Arena Sports Centre (A30)",
    suburb: "Camperdown",
    state: "NSW",
    address: "Western Ave, Camperdown NSW 2050",
    lat: -33.8876006,
    lng: 151.1862343,
    place_id: "ChIJZTOIRSuwEmsRqiBFxSraUYw",
    courts_badminton: null,
    courts_total: null,
    dedicated: false,
    surface: null,
    bookability: "public",
    booking_platform: "Sydney Uni Sport & Fitness online bookings",
    booking_url: "https://susf.com.au/online-bookings/",
    website_url: "https://susf.com.au/the-arena/",
    phone: "+61 2 9351 4978",
    opening_hours: { mon: [["06:30", "22:00"]], tue: [["06:30", "22:00"]], wed: [["06:30", "22:00"]], thu: [["06:30", "22:00"]], fri: [["06:30", "22:00"]], sat: [["08:00", "17:00"]], sun: [] },
    access_notes: "University of Sydney (SUSF) facility; badminton and squash share multipurpose courts inside the Arena gym complex. Distinct building from Sydney Uni Sport (SAC) and Robyn Webster Sports Centre.",
    price_bands: [
      { label: "Badminton off-peak", days: [1, 2, 3, 4, 5], cents: 2000, unit: "court_hour", notes: "From SUSF's price card; may be stale" },
      { label: "Badminton peak", days: [1, 2, 3, 4, 5, 6], cents: 3500, unit: "court_hour", notes: "From SUSF's price card; may be stale" },
    ],
    data_source: "operator",
    source_url: "https://susf.com.au/files/2022/05/18811_SYDUNI_2022-Brochures_Price-Cards_DL_Seperate_08.pdf",
    confidence: "medium",
  },
  {
    name: "Peter Forsyth Auditorium",
    suburb: "Glebe",
    state: "NSW",
    address: "Francis Street Corner, Franklyn St, Glebe NSW 2037",
    lat: -33.8831372,
    lng: 151.192711,
    place_id: "ChIJcc5FPSquEmsRZ2bdpm1UR_0",
    courts_badminton: null,
    courts_total: 1,
    dedicated: false,
    surface: "other",
    bookability: "public",
    booking_platform: "City of Sydney Spaces for Hire",
    booking_url: "https://www.cityofsydney.nsw.gov.au/sports-facilities/peter-forsyth-auditorium",
    website_url: "https://www.cityofsydney.nsw.gov.au/sports-facilities/peter-forsyth-auditorium",
    phone: null,
    opening_hours: { mon: [["07:00", "23:59"]], tue: [["07:00", "23:59"]], wed: [["07:00", "23:59"]], thu: [["07:00", "23:59"]], fri: [["07:00", "23:59"]], sat: [["07:00", "23:59"]], sun: [["07:00", "23:59"]] },
    access_notes: "City of Sydney-owned unstaffed community venue; single full-size carpeted multipurpose court hired as a whole (not per badminton court) for basketball, netball, volleyball, futsal and badminton — hirer sets up nets/lines themselves.",
    price_bands: [
      { label: "Weekday before 5pm", days: [1, 2, 3, 4, 5], cents: 7150, unit: "court_hour", notes: "Whole-venue rate, not per-court" },
      { label: "Weekday after 5pm / weekend / public holiday", days: [1, 2, 3, 4, 5, 6, 7], cents: 7800, unit: "court_hour", notes: "Whole-venue rate; community groups get 50% discount" },
    ],
    data_source: "operator",
    source_url: "https://www.cityofsydney.nsw.gov.au/sports-facilities/peter-forsyth-auditorium",
    confidence: "high",
  },

  // ---- upgrades to existing low-confidence rows from the A2 CSV seed (20260815001400) ----
  {
    slug: "nbc-silverwater",
    name: "NBC Silverwater",
    suburb: "Silverwater",
    state: "NSW",
    address: "2b/172 Silverwater Rd, Silverwater NSW 2128",
    lat: -33.8297323,
    lng: 151.048935,
    place_id: "ChIJVY2vV6CkEmsRojlIPBszEEY",
    courts_badminton: 6,
    courts_total: 6,
    dedicated: true,
    surface: "mat",
    bookability: "public",
    booking_platform: "yepbooking",
    booking_url: "https://nbc.yepbooking.com.au/",
    website_url: "https://nbcbadminton.com.au/",
    phone: null,
    opening_hours: null,
    access_notes: "Purpose-built badminton hall, part of NBC's 7-site Sydney network, 3-layer sprung timber floor with mat overlay. Confirmed casual/social sessions: Wed/Fri/Sun 8-11pm (Intermediate-Advanced). Full daily hours and general court-hire pricing not published.",
    price_bands: [],
    data_source: "operator",
    source_url: "https://nbc.yepbooking.com.au/",
    confidence: "medium",
  },
  {
    slug: "oran-park-leisure-centre",
    name: "Oran Park Leisure Centre",
    suburb: "Oran Park",
    state: "NSW",
    address: "74 Central Ave, Oran Park NSW 2570",
    lat: -33.9982816,
    lng: 150.7442833,
    place_id: "ChIJr4-HFgDzEmsRrh_7lybob4s",
    courts_badminton: null,
    courts_total: 4,
    dedicated: false,
    surface: "synthetic",
    bookability: "public",
    booking_platform: "ActiveCarrot",
    booking_url: "https://secure.activecarrot.com/login?site=1483",
    website_url: "https://oranparkleisurecentre.com.au/stadium-2/",
    phone: "(02) 4648 4831",
    opening_hours: { mon: [["05:30", "21:00"]], tue: [["05:30", "21:00"]], wed: [["05:30", "21:00"]], thu: [["05:30", "21:00"]], fri: [["05:30", "21:00"]], sat: [["07:00", "17:00"]], sun: [["07:00", "17:00"]] },
    access_notes: "Opened Oct 2024; 4-court multi-purpose stadium (run by Bluefit under Camden Council) shared with basketball and other sports. Equipment rental $2.50 each.",
    price_bands: [
      { label: "Community peak", days: [1, 2, 3, 4, 5], cents: 2550, unit: "court_hour", notes: null },
      { label: "Community off-peak", days: [1, 2, 3, 4, 5], cents: 2200, unit: "court_hour", notes: null },
      { label: "Commercial peak", days: [1, 2, 3, 4, 5, 6, 7], cents: 3050, unit: "court_hour", notes: null },
      { label: "Commercial off-peak", days: [1, 2, 3, 4, 5, 6, 7], cents: 2700, unit: "court_hour", notes: null },
    ],
    data_source: "operator",
    source_url: "https://oranparkleisurecentre.com.au/stadium-2/",
    confidence: "high",
  },
  {
    slug: "five-dock-leisure-centre",
    name: "Five Dock Leisure Centre",
    suburb: "Five Dock",
    state: "NSW",
    address: "William St, Five Dock NSW 2046",
    lat: -33.8684504,
    lng: 151.1181809,
    place_id: "ChIJfftkY626EmsRMH7oiDuxzsc",
    courts_badminton: 8,
    courts_total: 8,
    dedicated: true,
    surface: "synthetic",
    bookability: "public",
    booking_platform: "PlaySport / operator online booking",
    booking_url: "https://www.fdlc.com.au/indoor-sports/book-court/badminton",
    website_url: "https://www.fdlc.com.au/",
    phone: "9911 6300",
    opening_hours: { mon: [["09:00", "20:00"]], tue: [["09:00", "22:00"]], wed: [["09:00", "20:00"]], thu: [["09:00", "22:00"]], fri: [["09:00", "20:00"]], sat: [["08:00", "18:00"]], sun: [["09:00", "13:30"]] },
    access_notes: "Run by City of Canada Bay; 8 dedicated badminton courts, casual hourly hire up to 4 weeks ahead, 48hr cancellation policy, no cash on-site.",
    price_bands: [
      { label: "Peak", days: [1, 2, 3, 4, 5, 6, 7], cents: 3950, unit: "court_hour", notes: "Mon-Fri 4-10pm, all day Sat & Sun" },
      { label: "Off-peak", days: [1, 2, 3, 4, 5], cents: 2950, unit: "court_hour", notes: "Mon-Fri 6am-4pm" },
    ],
    data_source: "operator",
    source_url: "https://www.fdlc.com.au/indoor-sports/book-court/badminton",
    confidence: "high",
  },
  {
    slug: "sydney-olympic-park-sports-halls",
    name: "Sydney Olympic Park Sports Halls",
    suburb: "Sydney Olympic Park",
    state: "NSW",
    address: "Grand Parade, Sydney Olympic Park NSW 2127",
    lat: -33.8447036,
    lng: 151.0649008,
    place_id: "ChIJTbnXJ7ekEmsRrkWq1jmH2WI",
    courts_badminton: 12,
    courts_total: 12,
    dedicated: false,
    surface: "synthetic",
    bookability: "public",
    booking_platform: "Active Carrot",
    booking_url: "https://secure.activecarrot.com/public/facility/browse/487/924",
    website_url: "https://www.sydneyolympicpark.nsw.gov.au/things-to-see-and-do/badminton",
    phone: "02 9714 7600",
    opening_hours: { mon: [["16:00", "22:00"]], tue: [["12:00", "22:00"]], wed: [["12:00", "22:00"]], thu: [["12:00", "22:00"]], fri: [["16:00", "22:00"]], sat: [["08:00", "21:00"]], sun: [["08:00", "21:00"]] },
    access_notes: "12 badminton courts on synthetic Pulastic floor. Also used for basketball, volleyball, table tennis, pickleball, indoor soccer. Closed public holidays; parking fees apply.",
    price_bands: [{ label: "Badminton court hire", days: [1, 2, 3, 4, 5, 6, 7], cents: 3700, unit: "court_hour", notes: null }],
    data_source: "operator",
    source_url: "https://www.sydneyolympicpark.com.au/sports-halls/venue-information",
    confidence: "high",
  },
  {
    slug: "the-y-epping",
    name: "The Y NSW Epping",
    suburb: "Epping",
    state: "NSW",
    address: "15 Ward St, Epping NSW 2121",
    lat: -33.7716269,
    lng: 151.0683579,
    place_id: "ChIJYyRffKCmEmsRBhA3eTkbx6U",
    courts_badminton: null,
    courts_total: null,
    dedicated: false,
    surface: null,
    bookability: "public",
    booking_platform: "PerfectGym",
    booking_url: "https://theynsw.perfectgym.com.au",
    website_url: "https://www.ymcansw.org.au/centres/epping-ymca/court-hire/",
    phone: "02 9869 8966",
    opening_hours: { mon: [["05:30", "22:00"]], tue: [["05:30", "22:00"]], wed: [["05:30", "22:00"]], thu: [["05:30", "22:00"]], fri: [["05:30", "22:00"]], sat: [["07:00", "20:00"]], sun: [["07:00", "18:00"]] },
    access_notes: "Mixed-purpose multi-sport courts plus organised social badminton nights Mon-Thu. Equipment provided. Exact court count/surface not published.",
    price_bands: [
      { label: "Permanent court hire", days: [1, 2, 3, 4, 5, 6, 7], cents: 3500, unit: "court_hour", notes: "Recurring/permanent booking rate" },
      { label: "Casual court hire", days: [1, 2, 3, 4, 5, 6, 7], cents: 4000, unit: "court_hour", notes: "One-off casual booking rate" },
      { label: "Social badminton session", days: [1, 2, 3, 4], cents: 1200, unit: "person_session", notes: "Organised social nights Mon-Thu" },
    ],
    data_source: "operator",
    source_url: "https://www.ymcansw.org.au/centres/epping-ymca/court-hire/",
    confidence: "high",
  },
  {
    slug: "hurstville-aquatic-leisure-centre-stadium",
    name: "Hurstville Aquatic Leisure Centre",
    suburb: "Hurstville",
    state: "NSW",
    address: "King Georges Rd & Forest Rd, Hurstville NSW 2221",
    lat: -33.962871,
    lng: 151.0912935,
    place_id: "ChIJ-yzuE_DxtAERJLpF-aISBqM",
    courts_badminton: 3,
    courts_total: 3,
    dedicated: false,
    surface: null,
    bookability: "public",
    booking_platform: null,
    booking_url: null,
    website_url: "https://hurstvilleaquatic.com.au/stadium/",
    phone: "(02) 9585 9600",
    opening_hours: { mon: [["09:00", "22:30"]], tue: [["09:00", "22:30"]], wed: [["09:00", "22:30"]], thu: [["09:00", "22:30"]], fri: [["09:00", "22:30"]], sat: [["09:00", "20:00"]], sun: [["09:00", "20:00"]] },
    access_notes: "Stadium has 3 multi-purpose indoor courts with dividing nets; badminton set up on request. Bookings by phone or email stadium@hurstvilleaquatic.com.au. Also officially named 'The Johnny Warren Indoor Sports Centre' — same stadium, same place_id as a separate Places listing; not inserted as a duplicate row.",
    price_bands: [{ label: "Court hire", days: [1, 2, 3, 4, 5, 6, 7], cents: 3400, unit: "court_hour", notes: "Figure from a secondary directory, not confirmed on operator's own site — indicative only" }],
    data_source: "operator",
    source_url: "https://hurstvilleaquatic.com.au/stadium/",
    confidence: "high",
  },
  {
    slug: "ryde-community-sports-centre",
    name: "The Y NSW Ryde Community Sports Centre",
    suburb: "North Ryde",
    state: "NSW",
    address: "ELS Hall Park, Kent Rd, North Ryde NSW 2113",
    lat: -33.7874985,
    lng: 151.1126687,
    place_id: "ChIJt925qN6lEmsR3X6wGOiMGn8",
    courts_badminton: null,
    courts_total: 2,
    dedicated: false,
    surface: null,
    bookability: "unknown",
    booking_platform: "Gamz (formerly SportFix/Fixi)",
    booking_url: "https://gamzapp.com/RydeCommunitySportsCentre",
    website_url: "https://www.ymcansw.org.au/centres/ryde-community-sports-centre/",
    phone: "02 9878 2223",
    opening_hours: null,
    access_notes: "Y NSW's own sports-services page lists this as a badminton location (separate badminton contact line 02 8006 8509). 2 multi-purpose indoor courts (basketball/netball/soccer/badminton/volleyball) — unclear how many are badminton-marked at any time.",
    price_bands: [],
    data_source: "operator",
    source_url: "https://www.ymcansw.org.au/find-your-y/services/sports/",
    confidence: "medium",
  },
  {
    slug: "nbc-south-granville",
    name: "NBC Granville",
    suburb: "South Granville",
    state: "NSW",
    address: "3F/62 Ferndell St, South Granville NSW 2142",
    lat: -33.8688999,
    lng: 151.0070459,
    place_id: "ChIJjwsYQnm9EmsReMZxw1cZ8J8",
    courts_badminton: 14,
    courts_total: 14,
    dedicated: true,
    surface: null,
    bookability: "public",
    booking_platform: "yepbooking",
    booking_url: "https://nbc.yepbooking.com.au/",
    website_url: "https://nbcbadminton.com.au/",
    phone: null,
    opening_hours: null,
    access_notes: "One of NBC's 7 Sydney sites; NBC was Sydney's first facility fitted out exclusively for badminton (est. 2013). Books via the shared nbc.yepbooking.com.au platform. Per-site hours/phone/price not published by the operator; secondary sources conflict, so left blank rather than guessed.",
    price_bands: [],
    data_source: "operator",
    source_url: "https://nbcbadminton.com.au/",
    confidence: "medium",
  },
  {
    slug: "unsw-fitness-aquatic-centre",
    name: "UNSW Fitness & Aquatic Centre (FAC)",
    suburb: "Kensington",
    state: "NSW",
    address: "Fitness and Aquatic Centre (B5), Gate 2, High St, UNSW Sydney, Kensington NSW 2033",
    lat: -33.9154941,
    lng: 151.2265342,
    place_id: "ChIJDdkXWouxEmsRRnJ9dxHVtec",
    courts_badminton: 6,
    courts_total: null,
    dedicated: false,
    surface: null,
    bookability: "public",
    booking_platform: "PerfectGym",
    booking_url: "https://unswfac.perfectgym.com.au/ClientPortal2/#/FacilityBooking?clubId=1&zoneTypeId=15",
    website_url: "https://unswfac.com.au/facilities/badminton-courts/",
    phone: "(02) 9662 5112",
    opening_hours: { mon: [["06:00", "22:00"]], tue: [["06:00", "22:00"]], wed: [["06:00", "22:00"]], thu: [["06:00", "22:00"]], fri: [["06:00", "22:00"]], sat: [["07:00", "19:00"]], sun: [["07:00", "19:00"]] },
    access_notes: "6 mixed-purpose indoor courts hireable for badminton, open to students, staff and the wider public (not members-only). Bookable in person, by phone, or via the PerfectGym portal. UNSW Badminton Club also plays here (in the Unigym space above the FAC) — see existing access_notes addendum from the P1 halls pass.",
    price_bands: [{ label: "Court hire", days: [1, 2, 3, 4, 5, 6, 7], cents: 2800, unit: "court_hour", notes: "Flat rate, no peak/off-peak tiers found" }],
    data_source: "operator",
    source_url: "https://unswfac.com.au/facilities/badminton-courts/",
    confidence: "high",
  },
];

// Confirmed NOT to have badminton, or exact duplicates of a row already in VENUES above —
// deliberately not inserted. Kept here so a re-run of triage.mjs doesn't re-surface these as
// "unresearched."
const SKIPPED = [
  { name: "Marie Bashir Mosman Sports Centre", reason: "no_badminton — council site: single court configured for netball/basketball/indoor hockey/futsal only" },
  { name: "South Eveleigh Sports Courts", reason: "no_badminton — operator lists basketball/tennis/futsal only" },
  { name: "Entertainment Park", reason: "no_badminton — indoor go-kart/bowling/mini-golf/arcade complex" },
  { name: "Doohan Oval", reason: "no_badminton — outdoor tennis/netball/basketball/football reserve" },
  { name: "Warriewood Valley Sports Court", reason: "no_badminton — outdoor netball/basketball hard courts" },
  { name: "Quaycentre", reason: "no_badminton — gymnastics/basketball/indoor soccer/netball/volleyball venue; badminton is the separate Sports Halls venue (already enriched)" },
  { name: "St Marys Indoor Sports & Recreation", reason: "no_badminton — cricket/netball/soccer/touch football/dodgeball only" },
  { name: "St Clair Leisure Centre", reason: "no_badminton — basketball-oriented hall, no badminton found anywhere" },
  { name: "EZBOX Sports Eastwood", reason: "no_badminton — retail equipment store, not a venue with courts" },
  { name: "Penrith Indoor Sports and Recreation", reason: "no_badminton — indoor cricket/netball/soccer only" },
  { name: "Camellia Indoor Sports Centre", reason: "no_badminton — basketball/volleyball/futsal/netball/pickleball only; confirmed NOT the same as KBC Camellia" },
  { name: "Balmoral Rd Sports Complex", reason: "no_badminton — outdoor AFL/soccer/cricket fields + tennis + ball courts" },
  { name: "Johnny Warren Indoor Sports Centre", reason: "duplicate — same stadium as Hurstville Aquatic Leisure Centre (same address/phone/website)" },
  { name: "Alpha Slough / Alpha Badminton Centre - Slough Ave", reason: "duplicate — already inserted in the P1 chain pass (20260815001500)" },
  { name: "Bankstown City Sports Complex", reason: "no_badminton — outdoor netball/basketball/cricket park" },
  { name: "Pittwater Sports Centre", reason: "no_badminton — kids sport/fitness/physio/church/cafe complex" },
];

function venueStatement(r) {
  const slug = r.slug ?? slugify(r.name);
  const ctes = [
    `ins as (
  insert into public.venues (name, suburb, state, address, location, google_place_id, source, slug)
  values (${sqlStr(r.name)}, ${sqlStr(r.suburb)}, ${sqlStr(r.state)}, ${sqlStr(r.address)},
    extensions.ST_SetSRID(extensions.ST_MakePoint(${r.lng}, ${r.lat}), 4326), ${sqlStr(r.place_id)}, 'partner', ${sqlStr(slug)})
  on conflict (slug) do update set google_place_id = coalesce(public.venues.google_place_id, excluded.google_place_id)
  returning id
)`,
    `prof as (
  insert into public.venue_profiles (venue_id, courts_badminton, courts_total, dedicated, surface, bookability, club_contact, booking_platform, booking_url, website_url, phone, opening_hours, access_notes, data_source, source_url, confidence, verified_at)
  select id, ${r.courts_badminton ?? "null"}, ${r.courts_total ?? "null"}, ${sqlBool(r.dedicated)}, ${sqlStr(r.surface)}, ${sqlStr(r.bookability)}, ${sqlStr(r.club_contact ?? null)}, ${sqlStr(r.booking_platform)}, ${sqlStr(r.booking_url)}, ${sqlStr(r.website_url ?? null)}, ${sqlStr(r.phone)}, ${sqlJsonb(r.opening_hours)}, ${sqlStr(r.access_notes)}, ${sqlStr(r.data_source)}, ${sqlStr(r.source_url)}, ${sqlStr(r.confidence)}, now()
  from ins
  on conflict (venue_id) do update set
    courts_badminton = excluded.courts_badminton, courts_total = excluded.courts_total, dedicated = excluded.dedicated,
    surface = excluded.surface, bookability = excluded.bookability, club_contact = excluded.club_contact,
    booking_platform = excluded.booking_platform, booking_url = excluded.booking_url, website_url = excluded.website_url,
    phone = excluded.phone, opening_hours = excluded.opening_hours, access_notes = excluded.access_notes,
    data_source = excluded.data_source, source_url = excluded.source_url, confidence = excluded.confidence,
    verified_at = excluded.verified_at, updated_at = now()
  returning venue_id
)`,
  ];
  if (r.price_bands.length > 0) {
    ctes.push(`del_pricing as (
  delete from public.venue_pricing_bands where venue_id = (select id from ins) returning venue_id
)`);
    ctes.push(`ins_pricing as (
  insert into public.venue_pricing_bands (venue_id, label, days, starts_time, ends_time, cents, unit, notes)
  select ins.id, x.label, x.days, null, null, x.cents, x.unit, x.notes
  from ins, del_pricing, (values\n${r.price_bands.map((b) => `    (${sqlStr(b.label)}, ${sqlArr(b.days)}, ${b.cents}, ${sqlStr(b.unit)}, ${sqlStr(b.notes)})`).join(",\n")}\n  ) as x(label, days, cents, unit, notes)
  returning venue_id
)`);
  }
  const kind = r.slug ? "Upgrade existing" : "New";
  return `-- ${kind}: "${r.name}" (confidence: ${r.confidence})\nwith ${ctes.join(",\n")}\nselect id from ins;`;
}

const sections = [];
sections.push(`-- A6 (venues-plan.md §3): P2 enrichment pass. See data/venues/leads-to-enrich.csv (P2
-- rows) and the header comment in this script for the full stale-queue reconciliation.
-- Regenerate with: node scripts/venues/enrich-p2.mjs
--
-- Skipped (confirmed no badminton, or exact duplicate of a row inserted/updated below):
${SKIPPED.map((s) => `--   - ${s.name}: ${s.reason}`).join("\n")}
`);

for (const r of VENUES) sections.push(venueStatement(r));

const ts = "20260817000200";
const path = resolve(MIGRATIONS, `${ts}_p2_enrichment.sql`);
writeFileSync(path, sections.join("\n\n") + "\n");
const newCount = VENUES.filter((r) => !r.slug).length;
const updateCount = VENUES.filter((r) => r.slug).length;
console.log(`Wrote ${path}`);
console.log(`${newCount} new venue(s), ${updateCount} upgraded existing venue(s), ${SKIPPED.length} skipped.`);
